const swaggerJsdocOptions = {
  // List of files to be processes. You should include the route files where your annotations live.
  apis: ["./src/routes/*.js"],

  // Swagger definition. You can set values here or use package.json values.
  swaggerDefinition: {
    openapi: "3.1.0", // Specification (optional, defaults to swagger: '2.0')
    info: {
      title: "Package.json", // Title (required)
      version: "1.1.3", // Version (required)
      description: "Package.json - Express API with autogenerated swagger doc",
    },
  },
};

export default swaggerJsdocOptions;
